### PR TITLE
Use the new BetterInventoryExport command format

### PR DESCRIPTION
**Pull request by AngaBlue**
Updated the ws_inventory command to use the new BetterInventoryExport command format.

This involved removing the first argument `[all]` and updating the command validation accordingly.

### CODE REVIEW

**Comment by Bakkes** [comment]
Thanks! Not sure why i had the [all] parameter in there in the first place, and I guess it causes [issues ](https://github.com/Bakkes/BetterInventoryExport/blob/master/BetterInventoryExport/BetterInventoryExport.cpp#L140) with the actual better inventory export plugin. I'm not sure if I want the vcpkg dependency but the rest is a useful change. 
I won't really have the tools available to upgrade this plugin for the next few weeks, but will do so once I am back. Do you require this change now? If so, you should be able to work around it for now by calling `ws_inventory json json` (or csv csv) I think? Let me know!

Thanks for your contribution! I will keep this open until I can actually release it.

**Comment by AngaBlue** [comment]
I'm relatively new to Visual Studio so the vcpkg config was my way of adding websocketpp and asio.  I installed the dependencies through vcpkg and added the above config to link them.  I'm interested to know how you do it that doesn't require the same configuration.  Either way, I can remove the config changes if you'd rather not have them, just let me know.

And yes the work around you proposed seems to work.

**Comment by AngaBlue** [comment]
Hey @Bakkes , any update?

**Comment by Bakkes** [comment]
Instead of vcpkg, I'm linking against compiled libs currently. I think I'll keep that for now, but provide the binaries somehow. 
Could you remove the vcpkg dependency, and then I'll merge it in. I should be able to get it into the next BakkesMod update (which should be at the next RL update, unless that's very soon, since I'll be gone for another week or so).

**Comment by Bakkes** [comment]
Thanks! Will include it in today's update (after the RL update).

**Pull request merged**
